### ISSUE TITLE
CORE - 개발, 배포 환경 세팅

### ISSUE THREAD

**Issue by dl-00-e8** [Mews-MIS/Mews-Server-Test#1]
## IssueName
CORE - 개발환경 세팅

## Description
CI/CD 구축

## Todo
 - [x]  EC2 인스턴스, RDS, Elastic IP 생성
 - [x]  EC2 Docker 연결
 - [x]  Github Action
 - [x] jasypt 암호화 및 db 연동
 - [x] 깃허브 액션 jasypt 연동
 - [x] swagger 설정
 - [x] 에러처리 설정
 - [x] S3 설정

**Comment by ympark99** [comment]
jasypt 암호화 및 db 연동, 깃허브 액션 jasypt 연동 추가

**Comment by ympark99** [comment]
jasypt 암호화 및 db 연동, 깃허브 액션 jasypt 연동 완료

**Comment by ympark99** [comment]
swagger 설정 완료

**Comment by ympark99** [comment]
s3 연동 및 서버 배포 완료
