### ISSUE TITLE
뉴스 페이지 - 학사 일정 - 추가 사항

### ISSUE THREAD

**Issue by dl-00-e8** [Mews-MIS/Mews-Server-Test#17]
## IssueName
뉴스 페이지 - 학사 일정

## Description
학사 일정 칼럼 추가 및 추가 확인 사항에 따른 변경

## Todo
 - [x] 학사 일정 Entity 일정 종류, 시작 날짜, 종료 날짜 칼럼 추가
 - [x] 학사 일정 DTO 일정 종류별로 변경
 - [x] 학사 일정 등록 API 변경
 - [x] 학사 일정 조회 API 변경
 - [x] 학사 일정 수정 API Put -> Patch 변경

**Comment by dl-00-e8** [comment]
Merge 완료
