### ISSUE TITLE
큐레이션 - API

### ISSUE THREAD

**Issue by dl-00-e8** [Mews-MIS/Mews-Server-Test#40]
## IssueName
큐레이션 - API

## Description
큐레이션 API 개발

## Todo
 - [x] 큐레이션 등록 API
 - [x] 큐레이션 수정 API
 - [x] 큐레이션 삭제 API (patch mapping을 통한 삭제 여부 확인)
 - [x] 큐레이션 Get API
 - [ ] 큐레이션 페이지네이션 API
